version: "3.3"
services:
  telegram_video_bot:
    build: .
    restart: always
    environment:
      - DEV_NULL_CHAT=YOUR_DEV_NULL_CHAT
      - BOT_NAME=Video Bot
      - BOT_HANDLE=@YOUR_BOT_HANDLE
      - TOKEN_PATH=/token
    volumes:
      - ./token:/token
