version: "3.3"
services:
  telegram_video_bot:
    build: 
      context: .
      args:
        FFMPEG_URL: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
    restart: always
    container_name: telegram_video_bot
    environment:
      - DEV_NULL_CHAT=YOUR_DEV_NULL_CHAT
      - BOT_NAME=Video Bot
      - BOT_HANDLE=@YOUR_BOT_HANDLE
      - TOKEN_PATH=/token
    volumes:
      - ./token:/token
